resources:
  - name: spring-graalvm-native
    type: git
    source:
      uri: https://github.com/spring-projects-experimental/spring-graalvm-native
      branch: master
  - name: every-day
    type: time
    source: {interval: 24h}
jobs:
  - name: build-java8-key-samples
    public: true
    plan:
    - get: spring-graalvm-native
      trigger: true
    - task: build
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: springci/spring-graalvm-native
            tag: 20.3-dev-java8
        inputs:
          - name: spring-graalvm-native
        run:
          path: spring-graalvm-native/ci/build-key-samples.sh
  - name: build-java11-key-samples
    public: true
    plan:
      - get: spring-graalvm-native
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: springci/spring-graalvm-native
              tag: 20.3-dev-java11
          inputs:
            - name: spring-graalvm-native
          run:
            path: spring-graalvm-native/ci/build-key-samples.sh
  - name: build-20.3-dev-java8-samples
    public: true
    plan:
      - get: spring-graalvm-native
      - get: every-day
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: springci/spring-graalvm-native
              tag: 20.3-dev-java8
          inputs:
            - name: spring-graalvm-native
          run:
            path: spring-graalvm-native/ci/build-samples.sh
  - name: build-20.3-dev-java11-samples
    public: true
    plan:
      - get: spring-graalvm-native
      - get: every-day
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: springci/spring-graalvm-native
              tag: 20.3-dev-java11
          inputs:
            - name: spring-graalvm-native
          run:
            path: spring-graalvm-native/ci/build-samples.sh
  - name: build-master-java8-samples
    public: true
    plan:
      - get: spring-graalvm-native
      - get: every-day
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: springci/spring-graalvm-native
              tag: master-java8
          inputs:
            - name: spring-graalvm-native
          run:
            path: spring-graalvm-native/ci/build-samples.sh
  - name: build-master-java11-samples
    public: true
    plan:
      - get: spring-graalvm-native
      - get: every-day
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: springci/spring-graalvm-native
              tag: master-java11
          inputs:
            - name: spring-graalvm-native
          run:
            path: spring-graalvm-native/ci/build-samples.sh
  - name: deploy
    public: true
    plan:
      - get: spring-graalvm-native
        passed:
          - build-java8-key-samples
          - build-java11-key-samples
        trigger: true
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: openjdk
              tag: 11-jdk
          params:
            ARTIFACTORY_USERNAME:
            ARTIFACTORY_PASSWORD:
          inputs:
            - name: spring-graalvm-native
          run:
            path: spring-graalvm-native/ci/deploy.sh
        params:
          ARTIFACTORY_USERNAME: ((artifactory_username))
          ARTIFACTORY_PASSWORD: ((artifactory_password))
groups:
  - name: "each-commit-builds"
    jobs: [
      "build-java8-key-samples",
      "build-java11-key-samples",
      "deploy"]
  - name: "daily-builds"
    jobs: [
      "build-20.3-dev-java8-samples",
      "build-20.3-dev-java11-samples",
      "build-master-java8-samples",
      "build-master-java11-samples"]
