anchors:
  artifactory-repo-put-params: &artifactory-repo-put-params
    repo: libs-snapshot-local
    folder: distribution-repository
    build_uri: "https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
    build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
    disable_checksum_uploads: true
    exclude:
      - "**/*.effective-pom"
      - "*/spring-native-docs-*.jar"
  artifactory-task-params: &artifactory-task-params
    ARTIFACTORY_SERVER: ((artifactory-server))
    ARTIFACTORY_USERNAME: ((artifactory-username))
    ARTIFACTORY_PASSWORD: ((artifactory-password))
  docker-hub-task-params: &docker-hub-task-params
    DOCKER_HUB_USERNAME: ((docker-hub-username))
    DOCKER_HUB_PASSWORD: ((docker-hub-password))
  git-repo-resource-source: &git-repo-resource-source
    uri: ((github-repo))
    username: ((github-username))
    password: ((github-ci-release-token))
    branch: ((branch))
  registry-image-resource-source: &registry-image-resource-source
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: ((milestone))
  registry-mirror-vars: &registry-mirror-vars
    registry-mirror-host: ((registry-mirror-host))
    registry-mirror-username: ((registry-mirror-username))
    registry-mirror-password: ((registry-mirror-password))
  wavefront-params: &wavefront-params
    MANAGEMENT_METRICS_EXPORT_WAVEFRONT_APITOKEN: ((wavefront.api-token))
    MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI: ((wavefront.uri))
  slack-fail-params: &slack-fail-params
    text: >
      :concourse-failed: <https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|${BUILD_PIPELINE_NAME} ${BUILD_JOB_NAME} failed!>
    silent: true
    icon_emoji: ":concourse:"
    username: concourse-ci
resource_types:
  - name: artifactory-resource
    type: registry-image
    source:
      repository: springio/artifactory-resource
      tag: 0.0.14
  - name: github-release
    type: registry-image
    source:
      repository: concourse/github-release-resource
      tag: 1.5.5
  - name: pull-request
    type: registry-image
    source:
      repository: teliaoss/github-pr-resource
      tag: v0.23.0
  - name: slack-notification
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
resources:
  - name: git-repo
    type: git
    icon: github
    source:
      <<: *git-repo-resource-source
  - name: slack-alert
    type: slack-notification
    icon: slack
    source:
      url: ((slack-webhook-url))
  - name: ci-images-git-repo
    type: git
    icon: github
    source:
      <<: *git-repo-resource-source
      paths: ["ci/images/*"]
  - name: git-pull-request
    type: pull-request
    icon: source-pull
    source:
      access_token: ((github-ci-pull-request-token))
      repository: ((github-repo-name))
      base_branch: ((branch))
      ignore_paths: ["ci/*"]
  - name: graalvm-git-repo
    type: git
    icon: github
    source:
      uri: ((graalvm-repo))
      branch: ((graalvm-branch))
  - name: spring-native-ci-java11-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/spring-native-ci
      tag: java11-((milestone))
  - name: spring-native-ci-java17-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/spring-native-ci
      tag: java17-((milestone))
  - name: graalvm-ce-java11-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/graalvm-ce
      tag: java11-((milestone))
  - name: graalvm-ce-java17-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/graalvm-ce
      tag: java17-((milestone))
  - name: spring-native-java11-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/spring-native
      tag: java11-((milestone))
  - name: spring-native-java17-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/spring-native
      tag: java17-((milestone))
  - name: artifactory-repo
    type: artifactory-resource
    icon: package-variant
    source:
      uri: ((artifactory-server))
      username: ((artifactory-username))
      password: ((artifactory-password))
      build_name: ((build-name))
  - name: github-pre-release
    type: github-release
    icon: briefcase-download-outline
    source:
      owner: spring-projects-experimental
      repository: spring-native
      access_token: ((github-ci-release-token))
      pre_release: true
      release: false
  - name: github-release
    type: github-release
    icon: briefcase-download
    source:
      owner: spring-projects-experimental
      repository: spring-native
      access_token: ((github-ci-release-token))
      pre_release: false
  - name: every-day
    type: time
    source: {interval: 24h}
jobs:
  - name: build-spring-native-ci-java11-image
    old_name: build-ci-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
        trigger: true
      - task: build-spring-native-ci-image
        privileged: true
        file: git-repo/ci/tasks/build-spring-native-ci-image.yml
        output_mapping:
          image: spring-native-ci-java11-image
        vars:
          jdk-url: ((jdk-url-java11))
          ci-image-name: spring-native-ci-image
          <<: *registry-mirror-vars
      - put: spring-native-ci-java11-image
        params:
          image: spring-native-ci-java11-image/image.tar
  - name: build-spring-native-ci-java17-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
        trigger: true
      - task: build-spring-native-ci-image
        privileged: true
        file: git-repo/ci/tasks/build-spring-native-ci-image.yml
        output_mapping:
          image: spring-native-ci-java17-image
        vars:
          jdk-url: ((jdk-url-java17))
          ci-image-name: spring-native-ci-image
          <<: *registry-mirror-vars
      - put: spring-native-ci-java17-image
        params:
          image: spring-native-ci-java17-image/image.tar
  - name: check-graalvm-ce-change
    old_name: check-graalvm-ce-stable-change
    plan:
      - get: graalvm-git-repo
        trigger: true
  - name: check-graalvm-ce-every-day
    old_name: check-graalvm-ce-stable-every-day
    plan:
      - get: graalvm-git-repo
        passed: [check-graalvm-ce-change]
      - get: every-day
        trigger: true
  - name: build-graalvm-ce-java11-image
    old_name: build-graalvm-ce-stable-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
      - get: graalvm-git-repo
        passed: [check-graalvm-ce-every-day]
        trigger: true
      - get: every-day
        passed: [check-graalvm-ce-every-day]
      - task: build-graalvm-ce-image
        privileged: true
        file: git-repo/ci/tasks/build-graalvm-ce-image.yml
        output_mapping:
          image: graalvm-ce-java11-image
        vars:
          ci-image-name: graalvm-ce-image
          labsjdk-identifier: ((labsjdk-identifier-java11))
          graalvm-branch: ((graalvm-branch))
          <<: *registry-mirror-vars
      - put: graalvm-ce-java11-image
        params:
          image: graalvm-ce-java11-image/image.tar
  - name: build-graalvm-ce-java17-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
      - get: graalvm-git-repo
        passed: [ check-graalvm-ce-every-day ]
        trigger: true
      - get: every-day
        passed: [ check-graalvm-ce-every-day ]
      - task: build-graalvm-ce-image
        privileged: true
        file: git-repo/ci/tasks/build-graalvm-ce-image.yml
        output_mapping:
          image: graalvm-ce-java17-image
        vars:
          ci-image-name: graalvm-ce-image
          labsjdk-identifier: ((labsjdk-identifier-java17))
          graalvm-branch: ((graalvm-branch))
          <<: *registry-mirror-vars
      - put: graalvm-ce-java17-image
        params:
          image: graalvm-ce-java17-image/image.tar
  - name: build-spring-native-java11-image
    old_name: build-spring-native-stable-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
      - get: every-day
        passed: [build-graalvm-ce-java11-image]
        trigger: true
      - task: build-spring-native-image
        privileged: true
        file: git-repo/ci/tasks/build-spring-native-image.yml
        output_mapping:
          image: spring-native-java11-image
        vars:
          ci-image-name: spring-native-image
          base-image: "((docker-hub-organization))/graalvm-ce:java11-((milestone))"
          <<: *registry-mirror-vars
      - put: spring-native-java11-image
        params:
          image: spring-native-java11-image/image.tar
  - name: build-spring-native-java17-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
      - get: every-day
        passed: [ build-graalvm-ce-java17-image ]
        trigger: true
      - task: build-spring-native-image
        privileged: true
        file: git-repo/ci/tasks/build-spring-native-image.yml
        output_mapping:
          image: spring-native-java17-image
        vars:
          ci-image-name: spring-native-image
          base-image: "((docker-hub-organization))/graalvm-ce:java17-((milestone))"
          <<: *registry-mirror-vars
      - put: spring-native-java17-image
        params:
          image: spring-native-java17-image/image.tar
  - name: build-key-samples-java11
    public: true
    serial: true
    plan:
      - get: spring-native-java11-image
      - get: git-repo
        trigger: true
      - task: build
        privileged: true
        image: spring-native-java11-image
        file: git-repo/ci/tasks/build-key-samples.yml
        params:
          <<: *docker-hub-task-params
  - name: build-samples-aot-java11
    old_name: build-samples-aot-stable-java11
    public: true
    plan:
      - get: spring-native-java11-image
      - get: git-repo
      - get: every-day
        trigger: true
      - do:
        - task: build
          privileged: true
          image: spring-native-java11-image
          file: git-repo/ci/tasks/build-samples.yml
          params:
            AOT_ONLY: true
            <<: *docker-hub-task-params
            <<: *wavefront-params
  - name: build-samples-aot-java17
    public: true
    plan:
      - get: spring-native-java17-image
      - get: git-repo
      - get: every-day
        trigger: true
      - do:
          - task: build
            privileged: true
            image: spring-native-java17-image
            file: git-repo/ci/tasks/build-samples.yml
            params:
              AOT_ONLY: true
              <<: *docker-hub-task-params
              <<: *wavefront-params
  - name: build-samples-java11
    old_name: build-samples-stable-java11
    public: true
    plan:
      - get: spring-native-java11-image
      - get: git-repo
      - get: every-day
        trigger: true
      - do:
          - task: build
            privileged: true
            image: spring-native-java11-image
            file: git-repo/ci/tasks/build-samples.yml
            params:
              AOT_ONLY: false
              <<: *docker-hub-task-params
              <<: *wavefront-params
        on_failure:
          do:
            - put: slack-alert
              params:
                <<: *slack-fail-params
  - name: build-samples-java17
    public: true
    plan:
      - get: spring-native-java17-image
      - get: git-repo
      - get: every-day
        trigger: true
      - do:
          - task: build
            privileged: true
            image: spring-native-java17-image
            file: git-repo/ci/tasks/build-samples.yml
            params:
              AOT_ONLY: false
              <<: *docker-hub-task-params
              <<: *wavefront-params
  - name: deploy
    public: true
    plan:
      - get: spring-native-java11-image
      - get: git-repo
        passed:
          - build-key-samples-java11
        trigger: true
      - task: build-project
        image: spring-native-java11-image
        privileged: true
        timeout: ((task-timeout))
        file: git-repo/ci/tasks/build-project.yml
      - put: artifactory-repo
        params:
          <<: *artifactory-repo-put-params
  - name: build-pull-requests
    serial: true
    public: true
    plan:
      - get: spring-native-java11-image
      - get: git-repo
        resource: git-pull-request
        trigger: true
        version: every
      - do:
        - put: git-pull-request
          params:
            path: git-repo
            status: pending
        - task: build-project
          privileged: true
          image: spring-native-java11-image
          file: git-repo/ci/tasks/build-pr-project.yml
          params:
            <<: *docker-hub-task-params
            <<: *wavefront-params
        on_success:
          put: git-pull-request
          params:
            path: git-repo
            status: success
        on_failure:
          put: git-pull-request
          params:
            path: git-repo
            status: failure
  - name: stage-milestone
    serial: true
    plan:
      - get: spring-native-ci-java11-image
      - get: git-repo
        trigger: false
      - task: stage
        image: spring-native-java11-image
        file: git-repo/ci/tasks/stage.yml
        params:
          RELEASE_TYPE: M
      - put: artifactory-repo
        params:
          <<: *artifactory-repo-put-params
          repo: libs-staging-local
      - put: git-repo
        params:
          repository: stage-git-repo
  - name: stage-rc
    serial: true
    plan:
      - get: spring-native-ci-java11-image
      - get: git-repo
        trigger: false
      - task: stage
        image: spring-native-java11-image
        file: git-repo/ci/tasks/stage.yml
        params:
          RELEASE_TYPE: RC
      - put: artifactory-repo
        params:
          <<: *artifactory-repo-put-params
          repo: libs-staging-local
      - put: git-repo
        params:
          repository: stage-git-repo
  - name: stage-release
    serial: true
    plan:
      - get: spring-native-ci-java11-image
      - get: git-repo
        trigger: false
      - task: stage
        image: spring-native-java11-image
        file: git-repo/ci/tasks/stage.yml
        params:
          RELEASE_TYPE: RELEASE
      - put: artifactory-repo
        params:
          <<: *artifactory-repo-put-params
          repo: libs-staging-local
      - put: git-repo
        params:
          repository: stage-git-repo
  - name: promote-milestone
    serial: true
    plan:
      - get: spring-native-ci-java11-image
      - get: git-repo
        trigger: false
      - get: artifactory-repo
        trigger: false
        passed: [stage-milestone]
        params:
          download_artifacts: false
          save_build_info: true
      - task: promote
        image: spring-native-java11-image
        file: git-repo/ci/tasks/promote.yml
        params:
          RELEASE_TYPE: M
          <<: *artifactory-task-params
      - task: generate-changelog
        file: git-repo/ci/tasks/generate-changelog.yml
        params:
          RELEASE_TYPE: M
          GITHUB_USERNAME: ((github-username))
          GITHUB_TOKEN: ((github-ci-release-token))
        vars:
          <<: *registry-mirror-vars
      - put: github-pre-release
        params:
          name: generated-changelog/tag
          tag: generated-changelog/tag
          body: generated-changelog/changelog.md
  - name: promote-rc
    serial: true
    plan:
      - get: spring-native-ci-java11-image
      - get: git-repo
        trigger: false
      - get: artifactory-repo
        trigger: false
        passed: [stage-rc]
        params:
          download_artifacts: false
          save_build_info: true
      - task: promote
        image: spring-native-java11-image
        file: git-repo/ci/tasks/promote.yml
        params:
          RELEASE_TYPE: RC
          <<: *artifactory-task-params
      - task: generate-changelog
        file: git-repo/ci/tasks/generate-changelog.yml
        params:
          RELEASE_TYPE: RC
          GITHUB_USERNAME: ((github-username))
          GITHUB_TOKEN: ((github-ci-release-token))
        vars:
          <<: *registry-mirror-vars
      - put: github-pre-release
        params:
          name: generated-changelog/tag
          tag: generated-changelog/tag
          body: generated-changelog/changelog.md
  - name: promote-release
    serial: true
    plan:
      - get: spring-native-ci-java11-image
      - get: git-repo
        trigger: false
      - get: artifactory-repo
        trigger: false
        passed: [ stage-release ]
        params:
          download_artifacts: true
          save_build_info: true
      - task: promote
        image: spring-native-java11-image
        file: git-repo/ci/tasks/promote.yml
        params:
          RELEASE_TYPE: RELEASE
          <<: *artifactory-task-params
  - name: create-github-release
    serial: true
    plan:
      - get: spring-native-ci-java11-image
      - get: git-repo
      - get: artifactory-repo
        trigger: true
        passed: [ promote-release ]
        params:
          download_artifacts: false
          save_build_info: true
      - task: generate-changelog
        file: git-repo/ci/tasks/generate-changelog.yml
        params:
          RELEASE_TYPE: RELEASE
          GITHUB_USERNAME: ((github-username))
          GITHUB_TOKEN: ((github-ci-release-token))
        vars:
          <<: *registry-mirror-vars
      - put: github-release
        params:
          name: generated-changelog/tag
          tag: generated-changelog/tag
          body: generated-changelog/changelog.md
groups:
  - name: "builds"
    jobs: ["build-key-samples-java11", "deploy", "build-samples-aot-java11", "build-samples-aot-java17", "build-samples-java11", "build-samples-java17"]
  - name: "releases"
    jobs: ["stage-milestone", "stage-rc", "stage-release", "promote-milestone", "promote-rc", "promote-release", "create-github-release"]
  - name: "ci-images"
    jobs: ["build-spring-native-ci-java11-image", "build-spring-native-ci-java17-image", "check-graalvm-ce-change", "check-graalvm-ce-every-day", "build-graalvm-ce-java11-image", "build-graalvm-ce-java17-image", "build-spring-native-java11-image", "build-spring-native-java17-image" ]
  - name: "pull-requests"
    jobs: [ "build-pull-requests" ]
