anchors:
  artifactory-repo-put-params: &artifactory-repo-put-params
    repo: libs-snapshot-local
    folder: distribution-repository
    build_uri: "https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
    build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
    disable_checksum_uploads: true
    exclude:
      - "**/*.effective-pom"
      - "*/spring-native-docs-*.jar"
  docker-hub-task-params: &docker-hub-task-params
    DOCKER_HUB_USERNAME: ((docker-hub-username))
    DOCKER_HUB_PASSWORD: ((docker-hub-password))
  git-repo-resource-source: &git-repo-resource-source
    uri: ((github-repo))
    username: ((github-username))
    password: ((github-ci-release-token))
    branch: ((branch))
  registry-image-resource-source: &registry-image-resource-source
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: ((milestone))
  registry-mirror-vars: &registry-mirror-vars
    registry-mirror-host: ((registry-mirror-host))
    registry-mirror-username: ((registry-mirror-username))
    registry-mirror-password: ((registry-mirror-password))
  wavefront-params: &wavefront-params
    MANAGEMENT_METRICS_EXPORT_WAVEFRONT_APITOKEN: ((wavefront.api-token))
    MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI: ((wavefront.uri))
resources:
  - name: git-repo
    type: git
    icon: github
    source:
      <<: *git-repo-resource-source
  - name: ci-images-git-repo
    type: git
    icon: github
    source:
      <<: *git-repo-resource-source
      paths: ["ci/images/*"]
  - name: graalvm-git-repo
    type: git
    icon: github
    source:
      uri: ((graalvm-repo))
      branch: ((graalvm-branch))
  - name: spring-native-ci-java17-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/spring-native-ci
      tag: java17-((milestone))
  - name: graalvm-ce-java17-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/graalvm-ce
      tag: java17-((milestone))
  - name: spring-native-java17-image
    type: registry-image
    icon: docker
    source:
      <<: *registry-image-resource-source
      repository: ((docker-hub-organization))/spring-native
      tag: java17-((milestone))
  - name: every-day
    type: time
    source: {interval: 24h}
jobs:
  - name: build-spring-native-ci-java17-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
        trigger: true
      - task: build-spring-native-ci-image
        privileged: true
        file: git-repo/ci/tasks/build-spring-native-ci-image.yml
        output_mapping:
          image: spring-native-ci-java17-image
        vars:
          jdk-url: ((jdk-url-java17))
          ci-image-name: spring-native-ci-image
          <<: *registry-mirror-vars
      - put: spring-native-ci-java17-image
        params:
          image: spring-native-ci-java17-image/image.tar
  - name: check-graalvm-ce-change
    plan:
      - get: graalvm-git-repo
        trigger: true
  - name: check-graalvm-ce-every-day
    plan:
      - get: graalvm-git-repo
        passed: [check-graalvm-ce-change]
      - get: every-day
        trigger: true
  - name: build-graalvm-ce-java17-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
      - get: graalvm-git-repo
        passed: [ check-graalvm-ce-every-day ]
        trigger: true
      - get: every-day
        passed: [ check-graalvm-ce-every-day ]
      - task: build-graalvm-ce-image
        privileged: true
        file: git-repo/ci/tasks/build-graalvm-ce-image.yml
        output_mapping:
          image: graalvm-ce-java17-image
        vars:
          ci-image-name: graalvm-ce-image
          labsjdk-identifier: ((labsjdk-identifier-java17))
          graalvm-branch: ((graalvm-branch))
          <<: *registry-mirror-vars
      - put: graalvm-ce-java17-image
        params:
          image: graalvm-ce-java17-image/image.tar
  - name: build-spring-native-java17-image
    plan:
      - get: git-repo
      - get: ci-images-git-repo
      - get: every-day
        passed: [ build-graalvm-ce-java17-image ]
        trigger: true
      - task: build-spring-native-image
        privileged: true
        file: git-repo/ci/tasks/build-spring-native-image.yml
        output_mapping:
          image: spring-native-java17-image
        vars:
          ci-image-name: spring-native-image
          base-image: "((docker-hub-organization))/graalvm-ce:java17-((milestone))"
          <<: *registry-mirror-vars
      - put: spring-native-java17-image
        params:
          image: spring-native-java17-image/image.tar
  - name: build-samples-aot-java17
    public: true
    plan:
      - get: spring-native-java17-image
      - get: git-repo
      - get: every-day
        trigger: true
      - do:
          - task: build
            privileged: true
            image: spring-native-java17-image
            file: git-repo/ci/tasks/build-samples.yml
            params:
              AOT_ONLY: true
              <<: *docker-hub-task-params
              <<: *wavefront-params
  - name: build-samples-java17
    public: true
    plan:
      - get: spring-native-java17-image
      - get: git-repo
      - do:
          - task: build
            privileged: true
            image: spring-native-java17-image
            file: git-repo/ci/tasks/build-samples.yml
            params:
              AOT_ONLY: false
              <<: *docker-hub-task-params
              <<: *wavefront-params
groups:
  - name: "builds"
    jobs: ["build-samples-aot-java17", "build-samples-java17"]
  - name: "ci-images"
    jobs: ["build-spring-native-ci-java17-image", "check-graalvm-ce-change", "check-graalvm-ce-every-day", "build-graalvm-ce-java17-image", "build-spring-native-java17-image" ]
