anchors:
  slack-fail-params: &slack-fail-params
    text: >
      :concourse-failed: <https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}|${BUILD_PIPELINE_NAME} ${BUILD_JOB_NAME} failed!>
    silent: true
    icon_emoji: ":concourse:"
    username: concourse-ci
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
resources:
  - name: spring-native
    type: git
    source:
      uri: https://github.com/spring-projects-experimental/spring-native
      branch: master
  - name: slack-alert
    type: slack-notification
    icon: slack
    source:
      url: ((slack-webhook-url))
  - name: every-day
    type: time
    source: {interval: 24h}
jobs:
  - name: build-java8-key-samples
    public: true
    plan:
    - get: spring-native
      trigger: true
    - task: build
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: springci/spring-native
            tag: 21.0-dev-java8
        inputs:
          - name: spring-native
        run:
          path: spring-native/ci/build-key-samples.sh
  - name: build-java11-key-samples
    public: true
    plan:
      - get: spring-native
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: springci/spring-native
              tag: 21.0-dev-java11
          inputs:
            - name: spring-native
          run:
            path: spring-native/ci/build-key-samples.sh
  - name: build-21.0-dev-java8-samples
    old_name: build-20.3-dev-java8-samples
    public: true
    plan:
      - get: spring-native
      - get: every-day
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: springci/spring-native
              tag: 21.0-dev-java8
          inputs:
            - name: spring-native
          run:
            path: spring-native/ci/build-samples.sh
  - name: build-21.0-dev-java11-samples
    old_name: build-20.3-dev-java11-samples
    public: true
    plan:
      - get: spring-native
      - get: every-day
        trigger: true
      - do:
        - task: build
          config:
            platform: linux
            image_resource:
              type: registry-image
              source:
                repository: springci/spring-native
                tag: 21.0-dev-java11
            inputs:
              - name: spring-native
            run:
              path: spring-native/ci/build-samples.sh
        on_failure:
          do:
            - put: slack-alert
              params:
                <<: *slack-fail-params
  - name: build-master-java8-samples
    public: true
    plan:
      - get: spring-native
      - get: every-day
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: springci/spring-native
              tag: master-java8
          inputs:
            - name: spring-native
          run:
            path: spring-native/ci/build-samples.sh
  - name: build-master-java11-samples
    public: true
    plan:
      - get: spring-native
      - get: every-day
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: springci/spring-native
              tag: master-java11
          inputs:
            - name: spring-native
          run:
            path: spring-native/ci/build-samples.sh
  - name: deploy
    public: true
    plan:
      - get: spring-native
        passed:
          - build-java8-key-samples
          - build-java11-key-samples
        trigger: true
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: openjdk
              tag: 11-jdk
          params:
            ARTIFACTORY_USERNAME:
            ARTIFACTORY_PASSWORD:
          inputs:
            - name: spring-native
          run:
            path: spring-native/ci/deploy.sh
        params:
          ARTIFACTORY_USERNAME: ((artifactory-username))
          ARTIFACTORY_PASSWORD: ((artifactory-password))
groups:
  - name: "each-commit-builds"
    jobs: [
      "build-java8-key-samples",
      "build-java11-key-samples",
      "deploy"]
  - name: "daily-builds"
    jobs: [
      "build-21.0-dev-java8-samples",
      "build-21.0-dev-java11-samples",
      "build-master-java8-samples",
      "build-master-java11-samples"]
